{
 "title": "RUM",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "app_key", "label": "Applicação", "query": { "query": "label_values(appKey)" } }
  ]
 },
 "panels": [
  {
   "title": "Count Click Link ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (pageUrl, href) (rum_events_count_total{tagName=\"A\", appKey=\"$app_key\"}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Count Click Link",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (href, text) (rum_events_count_total{tagName=\"A\", appKey=\"$app_key\"}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Count Click Button",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (url) (rum_events_count_total{tagName=\"BUTTON\", appKey=\"$app_key\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Count Click Input",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (url) (rum_events_count_total{tagName=\"INPUT\", appKey=\"$app_key\"}) ",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}