services:
  grafana:
    image: grafana/otel-lgtm:0.11.5
    hostname: grafana
    #mage: grafana/otel-lgtm:0.10.1
    ports: 
      - 3000:3000
      - 4317:4317
      - 4318:4318
    volumes:
      - /home/smendesp/Dev/RUM/docker/volumes/grafana:/data
    #   - /home/smendesp/Dev/RUM/docker/volumes/otel-lgtm:/otel-lgtm

  rum-agent:
    image: rum-agent:latest
    hostname: rum-agent    
    ports: 
      - 9090:80
    
    depends_on:
      - grafana

  coletor:
    image: coletor:latest
    hostname: coletor
    ports: 
      - 8000:8000
    environment:
      - ENVIRONMENT=prd
      - DEBUG=False
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@192.168.68.114:5432/cys_core
      - SECRET_KEY=your-production-secret-key 
      - DB_DEFAULT_FORMAT_DATE=%Y-%m-%d %H:%M:%S 
      - WORKERS=1


      - INFLUXDB_URL=http://192.168.68.114:8181
      - INFLUXDB_DATABASE=_internal
      - INFLUXDB_TOKEN=apiv3_ycTA5tXFXZBpqjJFzqInhF3FgAj49Ag_HblCuX90R-5s1HPUTyNu1_wf1UNbhI_iSwIOXf_hi0OQx5lRNaaHCg

      - OTEL_SERVICE_NAME=auth-client
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_EXPORTER_OTLP_ENDPOINT=grafana:4317
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp

      - OTEL_BSP_SCHEDULE_DELAY=5000
      - OTEL_BSP_EXPORT_TIMEOUT=30000
      - OTEL_BSP_MAX_QUEUE_SIZE=2048
      - OTEL_BSP_MAX_EXPORT_BATCH_SIZE=512

      - OTEL_PYTHON_LOG_CORRELATION=true
      - OTEL_PYTHON_LOG_LEVEL=INFO
      - OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED=true       

    depends_on:
      - grafana

  kelly:
    image: kelly:latest
    ports: 
      - 9081:80
  
  influxdb-ui:
    image: influxdata/influxdb3-ui:1.2.1
    hostname: influxdb-ui
    ports:
      - 8888:80
      - 8889:8888
    environment:
      - INFLUXDB_UI_LOG_LEVEL=info
      #- INFLUXDB_UI_BIND_ADDRESS=:8888
      - INFLUXDB_UI_INFLUXDB_URL=http://influxdb3:8181
      - INFLUXDB_UI_INFLUXDB_TOKEN=smendesp:campos
      - INFLUXDB_UI_INFLUXDB_ORG=rum-org
      #- INFLUXDB_UI_INFLUXDB_BUCKET=my-bucket
    depends_on:
      - influxdb3

  influxdb3:
    image: influxdb:3-core
    hostname: influxdb3
    ports:
      - 8181:8181
    command:
      - influxdb3
      - serve
      - --node-id=node0
      - --object-store=file
      - --data-dir=/var/lib/influxdb3/data
      - --plugin-dir=/var/lib/influxdb3/plugins
    environment:
      - INFLUXD_HTTP_BIND_ADDRESS=:8181
      - INFLUXD_LOG_LEVEL=info
      - INFLUXD_STORAGE_ENGINE=tsm1
      - INFLUXD_DATA_QUERY_LOG_ENABLED=true
      - INFLUXD_DATA_QUERY_LOG_FILE_ENABLED=true
      - INFLUXD_DATA_QUERY_LOG_FILE_PATH=/var/lib/influxdb3/data/query.log
      - INFLUXD_DATA_QUERY_LOG_FILE_ROTATION_SIZE=104857600
      - INFLUXD_DATA_QUERY_LOG_FILE_ROTATION_COUNT=10
      - INFLUXD_DATA_RETENTION_CHECK_ENABLED=true
      - INFLUXD_DATA_RETENTION_CHECK_PERIOD=30m
      - INFLUXD_HTTP_FLUX_ENABLED=true
      - INFLUXD_HTTP_AUTH_ENABLED=false
      - INFLUXD_HTTP_PPROF_ENABLED=false
      - INFLUXD_HTTP_PPROF_BIND_ADDRESS=:6060
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=smendesp
      - DOCKER_INFLUXDB_INIT_PASSWORD=campos
      - DOCKER_INFLUXDB_INIT_ORG=rum-org
      #- DOCKER_INFLUXDB_INIT_BUCKET=my-bucket
    # volumes:
    #   - /home/smendesp/Dev/RUM/docker/vol/influxdb/data:/var/lib/influxdb3/data
    #   - /home/smendesp/Dev/RUM/docker/vol/influxdb/plugins:/var/lib/influxdb3/plugins

networks:
  default:
    name: rum-local-network
    #external: true