services:
  grafana:
    image: grafana/otel-lgtm:0.11.5
    hostname: grafana
    #mage: grafana/otel-lgtm:0.10.1
    ports: 
      - 3000:3000
      - 4317:4317
      - 4318:4318
    volumes:
      - /home/smendesp/Dev/RUM/docker/volumes/grafana:/data
    #   - /home/smendesp/Dev/RUM/docker/volumes/otel-lgtm:/otel-lgtm

  rum-agent:
    image: rum-agent:latest
    hostname: rum-agent    
    ports: 
      - 9090:80
    
    depends_on:
      - grafana

  coletor:
    image: coletor:latest
    hostname: coletor
    ports: 
      - 8000:8000
    environment:
      - ENVIRONMENT=prd
      - DEBUG=False
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@192.168.68.111:5432/cys_core
      - SECRET_KEY=your-production-secret-key 
      - DB_DEFAULT_FORMAT_DATE=%Y-%m-%d %H:%M:%S 
      - WORKERS=1

      - OTEL_SERVICE_NAME=auth-client
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_EXPORTER_OTLP_ENDPOINT=grafana:4317
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp

      - OTEL_BSP_SCHEDULE_DELAY=5000
      - OTEL_BSP_EXPORT_TIMEOUT=30000
      - OTEL_BSP_MAX_QUEUE_SIZE=2048
      - OTEL_BSP_MAX_EXPORT_BATCH_SIZE=512

      - OTEL_PYTHON_LOG_CORRELATION=true
      - OTEL_PYTHON_LOG_LEVEL=INFO
      - OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED=true       

    depends_on:
      - grafana

  kelly:
    image: kelly:latest
    ports: 
      - 9081:80

networks:
  default:
    name: rum-local-network
    #external: true